name: Deploy to VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  copy:
    name: Copy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: "20.204.64.17"
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "./"
        target: "SyncUs-tmp"
  deploy:
    name: "Deploy the latest files"
    runs-on: ubuntu-latest
    needs: copy
    steps:
    - name: "executing remote ssh commands"
      uses: appleboy/ssh-action@master
      with:
        host: "20.204.64.17"
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          sudo pm2 delete syncus
          cp -r -f ./SyncUs-tmp/* ./SyncUs
          rm -r SyncUs-tmp
          cd SyncUs
          source venv/bin/activate
          pip install -r requirements.txt
          deactivate
          sudo pm2 start app.py --no-autorestart --interpreter $(pwd)/venv/bin/python --name syncus
          sudo pm2 startup systemd
          sudo pm2 save